---
title: "Untitled"
author: "Vasiliy Zubarev"
date: "2025-04-23"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
Import libraries
```{r}
# Load the required libraries
library(ggplot2)
library("grid")
library(ggpubr)
```

Plot for genome-mode BUSCOs
```{r}
# !!! CONFIGURE YOUR PLOT HERE !!! 
# Output
my_output <- paste("/gpfs/data/gpfs0/vasiliy.zubarev/Sponge/Analysis/2025_04_23_compleasm","busco_figure.png",sep="/") 
my_width <- 20
my_height <- 10
my_unit <- "cm"

# Colors
my_colors <- c("#56B4E9", "#3492C7", "#F0E442", "#F04442")
# Bar height ratio
my_bar_height <- 0.75

# Legend
my_title <- "metazoa_odb12, genome mode"

# Font
my_family <- "sans"
my_size_ratio <- 1

# !!! SEE YOUR DATA HERE !!! 
# Your data as generated by python, remove or add more
my_species <- c('Halisarca dujardinii', 'Halisarca dujardinii', 'Halisarca dujardinii', 'Halisarca dujardinii', 'Amphimedon queenslandica', 'Amphimedon queenslandica', 'Amphimedon queenslandica', 'Amphimedon queenslandica', 'Corticum candelabrum', 'Corticum candelabrum', 'Corticum candelabrum', 'Corticum candelabrum', 'Dysidea avara', 'Dysidea avara', 'Dysidea avara', 'Dysidea avara', 'Halichondria panicea', 'Halichondria panicea', 'Halichondria panicea', 'Halichondria panicea', 'Oscarella lobularis', 'Oscarella lobularis', 'Oscarella lobularis', 'Oscarella lobularis', 'Sycon ciliatum', 'Sycon ciliatum', 'Sycon ciliatum', 'Sycon ciliatum')
my_species <- factor(my_species)
my_species <- factor(my_species,levels(my_species)[c(7,6,4,3,2,1,5)]) # reorder your species here just by changing the values in the vector :
my_percentage <- c(77.08, 1.79, 6.70, 14.43, 75.00, 2.53, 9.08, 13.39, 86.61, 0.60, 5.65, 7.14, 81.25, 1.04, 4.46, 13.24, 82.89, 1.19, 4.76, 11.16, 83.48, 1.04, 5.95, 9.52, 75.15, 1.19, 6.70, 16.96)
my_values <- c(518, 12, 45, 97, 504, 17, 61, 90, 582, 4, 38, 48, 546, 7, 30, 89, 557, 8, 32, 75, 561, 7, 40, 64, 505, 8, 45, 114)

######################################
######################################
######################################
# Code to produce the graph
labsize = 1
if (length(levels(my_species)) > 10){
 labsize = 0.66
}
print("Plotting the figure ...")
category <- c(rep(c("S","D","F","M"),c(1)))
category <-factor(category)
category = factor(category,levels(category)[c(4,1,2,3)])
df = data.frame(my_species,my_percentage,my_values,category)

figure1 <- ggplot() + 
  
  geom_bar(aes(y = my_percentage, x = my_species, fill = category), position = position_stack(reverse = TRUE), data = df, stat="identity", width=my_bar_height) + 
  coord_flip() + 
  theme_gray(base_size = 8) + 
  scale_y_continuous(labels = c("0","20","40","60","80","100"), breaks = c(0,20,40,60,80,100)) + 
  scale_fill_manual(values = my_colors,labels =c(" Complete (C) and single-copy (S)  ",
                                                 " Complete (C) and duplicated (D)",
                                                 " Fragmented (F)  ",
                                                 " Missing (M)")) +   
  ggtitle(my_title) + 
  xlab("") + 
  ylab("\n%BUSCOs") + 

  theme(plot.title = element_text(family=my_family, hjust=0.5, colour = "black", size = rel(2.2)*my_size_ratio, face = "bold")) + 
  theme(legend.position="top",legend.title = element_blank()) + 
  theme(legend.text = element_text(family=my_family, size = rel(1.2)*my_size_ratio)) + 
  theme(panel.background = element_rect(color="#FFFFFF", fill="white")) + 
  theme(panel.grid.minor = element_blank()) + 
  theme(panel.grid.major = element_blank()) +
  theme(axis.text.y = element_text(family=my_family, colour = "black", size = rel(1.66)*my_size_ratio)) + 
  theme(axis.text.x = element_text(family=my_family, colour = "black", size = rel(1.66)*my_size_ratio)) + 
  theme(axis.line = element_line(size=1*my_size_ratio, colour = "black")) + 
  theme(axis.ticks.length = unit(.85, "cm")) + 
  theme(axis.ticks.y = element_line(colour="white", size = 0)) + 
  theme(axis.ticks.x = element_line(colour="#222222")) + 
  theme(axis.ticks.length = unit(0.4, "cm")) + 
  theme(axis.title.x = element_text(family=my_family, size=rel(1.2)*my_size_ratio)) + 
  
  guides(fill = guide_legend(override.aes = list(colour = NULL))) +
  guides(fill=guide_legend(nrow=2,byrow=TRUE))
  
  for(i in rev(c(1:length(levels(my_species))))){
    detailed_values <- my_values[my_species==my_species[my_species==levels(my_species)[i]]]
    total_buscos <- sum(detailed_values)
    figure1 <- figure1 + 
    annotate("text", label=paste("C:", detailed_values[1] + detailed_values[2], " [S:", detailed_values[1], ", D:", detailed_values[2], "], F:", detailed_values[3], ", M:", detailed_values[4], ", n:", total_buscos, sep=""), 
             y=3, x = i, size = labsize*4*my_size_ratio, colour = "black", hjust=0, family=my_family)
  }

figure1  
#ggsave(figure, file=my_output, width = my_width, height = my_height, unit = my_unit)
#print("Done")
```

Plot for protein-mode BUSCOs
```{r}

# !!! CONFIGURE YOUR PLOT HERE !!! 
# Output
my_output <- paste("/gpfs/data/gpfs0/vasiliy.zubarev/Sponge/Analysis/2025_04_23_compleasm","busco_figure.png",sep="/") 
my_width <- 20
my_height <- 20
my_unit <- "cm"

# Colors
my_colors <- c("#56B4E9", "#3492C7", "#F0E442", "#F04442")
# Bar height ratio
my_bar_height <- 0.75

# Legend
my_title <- "metazoa_odb12, protein mode"

# Font
my_family <- "sans"
my_size_ratio <- 1

# !!! SEE YOUR DATA HERE !!! 
# Your data as generated by python, remove or add more
my_species <- c('Amphimedon queenslandica', 'Amphimedon queenslandica', 'Amphimedon queenslandica', 'Amphimedon queenslandica', 'Corticum candelabrum', 'Corticum candelabrum', 'Corticum candelabrum', 'Corticum candelabrum', 'Dysidea avara', 'Dysidea avara', 'Dysidea avara', 'Dysidea avara', 'Halichondria panicea', 'Halichondria panicea', 'Halichondria panicea', 'Halichondria panicea', 'Halisarca dujardinii', 'Halisarca dujardinii', 'Halisarca dujardinii', 'Halisarca dujardinii', 'Oscarella lobularis', 'Oscarella lobularis', 'Oscarella lobularis', 'Oscarella lobularis', 'Sycon ciliatum', 'Sycon ciliatum', 'Sycon ciliatum', 'Sycon ciliatum')
my_species <- factor(my_species)
my_species <- factor(my_species,levels(my_species)[c(7,6,4,3,2,1,5)]) # reorder your species here just by changing the values in the vector :
my_percentage <- c(68.30, 18.75, 7.29, 5.65, 65.92, 23.21, 6.55, 4.32, 64.29, 26.04, 3.87, 5.80, 65.92, 23.96, 3.72, 6.40, 61.90, 24.70, 6.10, 7.29, 69.20, 20.54, 4.17, 6.10, 70.24, 15.92, 4.61, 9.23)
my_values <- c(459, 126, 49, 38, 443, 156, 44, 29, 432, 175, 26, 39, 443, 161, 25, 43, 416, 166, 41, 49, 465, 138, 28, 41, 472, 107, 31, 62)

######################################
######################################
######################################
# Code to produce the graph
labsize = 1
if (length(levels(my_species)) > 10){
 labsize = 0.66
}
print("Plotting the figure ...")
category <- c(rep(c("S","D","F","M"),c(1)))
category <-factor(category)
category = factor(category,levels(category)[c(4,1,2,3)])
df = data.frame(my_species,my_percentage,my_values,category)

figure2 <- ggplot() + 
  
  geom_bar(aes(y = my_percentage, x = my_species, fill = category), position = position_stack(reverse = TRUE), data = df, stat="identity", width=my_bar_height) + 
  coord_flip() + 
  theme_gray(base_size = 8) + 
  scale_y_continuous(labels = c("0","20","40","60","80","100"), breaks = c(0,20,40,60,80,100)) + 
  scale_fill_manual(values = my_colors,labels =c(" Complete (C) and single-copy (S)  ",
                                                 " Complete (C) and duplicated (D)",
                                                 " Fragmented (F)  ",
                                                 " Missing (M)")) +   
  ggtitle(my_title) + 
  xlab("") + 
  ylab("\n%BUSCOs") + 

  theme(plot.title = element_text(family=my_family, hjust=0.5, colour = "black", size = rel(2.2)*my_size_ratio, face = "bold")) + 
  theme(legend.position="top",legend.title = element_blank()) + 
  theme(legend.text = element_text(family=my_family, size = rel(1.2)*my_size_ratio)) + 
  theme(panel.background = element_rect(color="#FFFFFF", fill="white")) + 
  theme(panel.grid.minor = element_blank()) + 
  theme(panel.grid.major = element_blank()) +
  theme(axis.text.y = element_text(family=my_family, colour = "black", size = rel(1.66)*my_size_ratio)) + 
  theme(axis.text.x = element_text(family=my_family, colour = "black", size = rel(1.66)*my_size_ratio)) + 
  theme(axis.line = element_line(size=1*my_size_ratio, colour = "black")) + 
  theme(axis.ticks.length = unit(.85, "cm")) + 
  theme(axis.ticks.y = element_line(colour="white", size = 0)) + 
  theme(axis.ticks.x = element_line(colour="#222222")) + 
  theme(axis.ticks.length = unit(0.4, "cm")) + 
  theme(axis.title.x = element_text(family=my_family, size=rel(1.2)*my_size_ratio)) + 
  
  guides(fill = guide_legend(override.aes = list(colour = NULL))) +
  guides(fill=guide_legend(nrow=2,byrow=TRUE))
  
  for(i in rev(c(1:length(levels(my_species))))){
    detailed_values <- my_values[my_species==my_species[my_species==levels(my_species)[i]]]
    total_buscos <- sum(detailed_values)
    figure2 <- figure2 + 
    annotate("text", label=paste("C:", detailed_values[1] + detailed_values[2], " [S:", detailed_values[1], ", D:", detailed_values[2], "], F:", detailed_values[3], ", M:", detailed_values[4], ", n:", total_buscos, sep=""), 
             y=3, x = i, size = labsize*4*my_size_ratio, colour = "black", hjust=0, family=my_family)
  }

figure2  
#ggsave(figure, file=my_output, width = my_width, height = my_height, unit = my_unit)
#print("Done")
```


```{r}
ggarrange(figure1, figure2, 
          labels = c("A", "B"),
          ncol = 2, nrow = 1)
ggsave('compleasm.pdf', height = 7, width = 14)
```
